### ISSUE TITLE
idp로부터 발급받은 jwt를 서버에 전달해서 유저 정보를 받아온다.

### ISSUE THREAD

**Issue by SeolyeongBae** [gsainfoteam/gistalk-be-legacy#52]
**요구사항 : idp로 로그인한 뒤 유저 정보를 받아오고 싶습니다.(uuid, 유저 이름, 이메일, 학번 등)**

현재 프론트엔드에서
idp로 로그인 -> auth_code 발급 -> 해당 코드로 jwt를 발급받아 저장
까지 하고 있습니다. 

이에 jwt를 서버에 보내 유저 정보를 받아오고 싶은데, client id 같은 secret key와 같은 정보를 필요로 합니다.
따라서 프론트엔드보다 백단에서 처리하는게 적절하다고 생각합니다.

**Comment by minjunj** [comment]
현재 idp로 로그인 -> access_token 발급 -> 해당 토큰을 지스톡에 전달-> 지스톡 용 access token 발급
순으로 백단에서 cliend id, secret key를 환경변수로 담아 처리하였습니다.
유저 정보를 원한다면 지스톡에서 발급받은 토큰을
/user/info 로 post 요청을 하면 유저 uuid와 email을 반환할 것 입니다.
